steps:

- name: 'gcr.io/cloud-builders/docker'
  id: setup_env
  entrypoint: bash
  args:
    - -e
    - -c
    - |
      cp /workspace/backend/infra/.env.$_APP_ENV /workspace/backend/app/.env
      sed -i \
        -e "s|APP_ENV=|APP_ENV=$$_APP_ENV|g" \
        /workspace/backend/app/.env
  # secretEnv: ['']
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: builder_image
  args: [
    'build',
    '--target', 'builder',
    '-f', '/workspace/backend/infra/Dockerfile',
    '-t', 'github.com/woriheck/go-commerce:builder',
    '.'
  ]
  waitFor: ['setup_env']

- name: 'gcr.io/cloud-builders/docker'
  id: final_image
  args: [
    'build',
    '-f', '/workspace/backend/infra/Dockerfile.prod',
    '-t', '$_IMAGE_URI',
    '.'
  ]
  waitFor: [builder_image]

- name: 'gcr.io/cloud-builders/docker'
  id: push_image
  args: ['push', '$_IMAGE_URI']
  waitFor: [final_image]

# - name: 'gcr.io/cloud-builders/gcloud-slim'
#   entrypoint: bash
#   args:
#     - -c
#     - |
#       gcloud run deploy $_SERVICE_NAME \
#         --region $_REGION \
#         --image $_IMAGE_URI \
#         --service-account $_SERVICE_ACCOUNT \
#         --add-cloudsql-instances $_CLOUD_SQL_CONNECTION \
#         --allow-unauthenticated \
#         --vpc-connector=default-vpc-connector \
#         --vpc-egress=all-traffic \
#         --quiet
        
#   waitFor: ['push_image']

# options:
#   dynamic_substitutions: true

substitutions:
#     _CLOUD_SQL_CONNECTION: ${PROJECT_ID}:asia-northeast1:dev-jtb-b2b
    _IMAGE_URI: gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${SHORT_SHA}
#     _GITHUB_BUCKET: jtb-b2b-account-github
#     _REGION: asia-northeast1
#     _SERVICE_ACCOUNT: dev-account-cloudrun-app@${PROJECT_ID}.iam.gserviceaccount.com

    # Set this value on cloud trigger to create a separate environment for dev
    # APP_ENV: dev
    _SERVICE_NAME: go-commerce

# availableSecrets:
#   secretManager:
#   - versionName: projects/${PROJECT_ID}/secrets/DB_PASSWORD/versions/latest
#     env: 'DB_PASSWORD'
