steps:

- name: 'gcr.io/cloud-builders/docker'
  id: setup_env
  entrypoint: bash
  args:
    - -e
    - -c
    - |
      cp /workspace/backend/infra/.env.$_APP_ENV /workspace/backend/app/.env
      sed -i \
        -e "s|APP_ENV=|APP_ENV=$$_APP_ENV|g" \
        /workspace/backend/app/.env
  # secretEnv: ['']
  waitFor: ['-']

- name: 'gcr.io/kaniko-project/executor:latest'
  id: builder_image
  args:
  - --destination=$_IMAGE_URI:builder
  - --dockerfile=/workspace/backend/infra/Dockerfile
  - --context-sub-path=./build
  - --cache=false
  - --cache-ttl=1h
  waitFor: ['setup_env']
  
# - name: 'gcr.io/cloud-builders/docker'
#   id: builder_image
#   args: [
#     'build',
#     '--target', 'builder',
#     '-f', '/workspace/backend/infra/Dockerfile',
#     '-t', '$_IMAGE_URI:builder',
#     './backend'
#   ]
#   waitFor: ['setup_env']

- name: 'gcr.io/cloud-builders/docker'
  id: final_image
  args: [
    'build',
    '-f', '/workspace/backend/infra/Dockerfile.prod',
    '-t', '$_IMAGE_URI:${SHORT_SHA}',
    './backend'
  ]
  waitFor: [builder_image]

- name: 'gcr.io/cloud-builders/docker'
  id: push_image
  args: ['push', '$_IMAGE_URI']
  waitFor: [final_image]

- name: 'gcr.io/cloud-builders/gcloud-slim'
  entrypoint: bash
  args:
    - -c
    - |
      gcloud run deploy $_APP_ENV-$_SERVICE_NAME \
        --region $_REGION \
        --image $_IMAGE_URI:${SHORT_SHA} \
        --service-account $_SERVICE_ACCOUNT \
        --allow-unauthenticated \
        --quiet
        
  waitFor: ['push_image']

# options:
#   dynamic_substitutions: true

substitutions:
#     _CLOUD_SQL_CONNECTION: ${PROJECT_ID}:asia-northeast1:dev-jtb-b2b
    _IMAGE_URI: gcr.io/${PROJECT_ID}/${_SERVICE_NAME}
#     _GITHUB_BUCKET: jtb-b2b-account-github
    _REGION: asia-southeast1
    _SERVICE_ACCOUNT: run-backend@go-commerce-349201.iam.gserviceaccount.com

    # Set this value on cloud trigger to create a separate environment for dev
    # APP_ENV: dev
    _SERVICE_NAME: backend

# availableSecrets:
#   secretManager:
#   - versionName: projects/${PROJECT_ID}/secrets/DB_PASSWORD/versions/latest
#     env: 'DB_PASSWORD'
